<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit37d91d3f355272496854b61d72fa2efd
{
    public static $prefixesPsr0 = array (
        'F' => 
        array (
            'FtpClient' => 
            array (
                0 => __DIR__ . '/..' . '/nicolab/php-ftp-client/src',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit37d91d3f355272496854b61d72fa2efd::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit37d91d3f355272496854b61d72fa2efd::$classMap;

        }, null, ClassLoader::class);
    }
}
