<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitc97f2571197b95ded283b06a74b3c696
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PayPal' => 
            array (
                0 => __DIR__ . '/..' . '/paypal/rest-api-sdk-php/lib',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitc97f2571197b95ded283b06a74b3c696::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitc97f2571197b95ded283b06a74b3c696::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInitc97f2571197b95ded283b06a74b3c696::$prefixesPsr0;
            $loader->classMap = ComposerStaticInitc97f2571197b95ded283b06a74b3c696::$classMap;

        }, null, ClassLoader::class);
    }
}
