<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitd01a04897287ccdead8869bae3db8ebe
{
    public static $prefixLengthsPsr4 = array (
        'Y' => 
        array (
            'Yabacon\\' => 8,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Yabacon\\' => 
        array (
            0 => __DIR__ . '/..' . '/yabacon/paystack-php/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitd01a04897287ccdead8869bae3db8ebe::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitd01a04897287ccdead8869bae3db8ebe::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitd01a04897287ccdead8869bae3db8ebe::$classMap;

        }, null, ClassLoader::class);
    }
}
