<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6c9a782523183bfc1cfc8a3c2ed814dd
{
    public static $prefixLengthsPsr4 = array (
        'R' => 
        array (
            'Razorpay\\Tests\\' => 15,
            'Razorpay\\Api\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Razorpay\\Tests\\' => 
        array (
            0 => __DIR__ . '/..' . '/razorpay/razorpay/tests',
        ),
        'Razorpay\\Api\\' => 
        array (
            0 => __DIR__ . '/..' . '/razorpay/razorpay/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'R' => 
        array (
            'Requests' => 
            array (
                0 => __DIR__ . '/..' . '/rmccue/requests/library',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6c9a782523183bfc1cfc8a3c2ed814dd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6c9a782523183bfc1cfc8a3c2ed814dd::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit6c9a782523183bfc1cfc8a3c2ed814dd::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit6c9a782523183bfc1cfc8a3c2ed814dd::$classMap;

        }, null, ClassLoader::class);
    }
}
